version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: socialMedia
    ports:
      - 5433:5432  # Mapping the container's port 5432 to the host's port 5433
    expose:
      - 5433
      - 5432

networks:
  demo_network: # Creating a network called-demo_network
    driver: bridge
